### PR TITLE
🐛 integrate formatter with monaco, unbind editor

### PR DESCRIPTION
**Pull request by modderme123**
now the command palette (`F1`) also uses the prettier formatter, and I think I got rid of the flickering

### CODE REVIEW

**Comment by modderme123** [comment]
Whoops, just realized that the output isn't being set anymore. I need to set the output model on build

**Comment by amoutonbrady** [comment]
Awesome work! It feels soooo smooth now without the flickering.

This PR seems all good, and the following remarks are out of the scope of this but here's a couple of things that might be annoying/blocking for me to merge this branch into master :\

- When hovering over an error that's near the top, the hover popup seems to be blocked... It's probably an overflow / z-index kind of thing but I couldn't find it locally.  At first I thought it was this one here: https://github.com/ryansolid/solid-playground/blob/monaco-pnpm-vite/src/components/editor/index.tsx#L78 but reverting to an `overflow-auto` + `z-50` didn't seem to fix it
image

- A bit more critically, the fact that we TS check now mean we see this annoying error for `.tsx` extension. Searching a bit through some TS issues, it doesn't seem like there's a way around... One thing however that we can at least do is detecting the extension in the import name and removing it here https://github.com/ryansolid/solid-playground/blob/monaco-pnpm-vite/src/workers/compiler.ts#L47 by simply doing `return importee.replace('.tsx', '') + '.tsx';`

**Comment by modderme123** [comment]
The way the import is set up right now is to allow importing from `./tab1` (without the tsx)

I'll create a pr with hovering and jsx highlighting once I figure those out

**Comment by amoutonbrady** [comment]
Yeah and that's arguably a better DX, less typing all the way. The problem is that until your PR, it was required to have `.tsx` and for retrocompatibility reasons I guess it should at least compile (which right now it doesn't but can be quickly fixed with the bit of code I mentioned above).

Would you rather keep working on the PR or open a new one?

**Comment by modderme123** [comment]
I'll add the tsx change and then open a new pr for the rest

**Comment by modderme123** [comment]
I found the problem with z-indexing but somehow broke css grids in the process (there was another overflow auto)

**Comment by amoutonbrady** [comment]
Alright, with the tsx issue taken care of, let's close this one and fix the rest in another PR. Again, great work!

**Pull request merged**
