### PR TITLE
:fire: Vite, Monaco, pnpm

### PR DESCRIPTION
**Pull request by modderme123**
I'm open to any changes & bugs that need to be fixed. Just thought I'd put this here now that I've figured out how to automatically patch Vite when using pnpm

### CODE REVIEW

**Comment by modderme123** [comment]
I realize that this is a lot of changes. If there is any way you want me to break it up or get rid of parts, I can try to do that

**Comment by amoutonbrady** [comment]
Wow! Just ran it locally this is amazing. Fantastic job. Vite + Windicss makes it sooooooooo fast. At least in dev. Build is another story and feels a bit unpredictable with tons of warning thrown.

Here are some of the things I noticed :
* I guess trying to make monaco controlled via two way binding isn't.. that good, it flickers a bit
* The theme doesn't play well with JSX it seems
* The build increased a lot but I guess once it's cached, it's fine

I think I'll merge this and polish the few minor styling issues and probably release it. That's amazing again. Thanks for your work.

**Comment by modderme123** [comment]
Thanks! I think the warnings you see in build are because of some global `this` in monaco. I've tested it and they don't seem to cause any issues, but I agree that it would be better if they weren't there and the build was faster

* I missed the flickering of curly brackets when I was editing before. I'll look at trying to fix it, probably just by removing the two way binding.
* What do you mean by the theme not playing well with JSX? Do you mean the window on the right doesn't show text as easily in dark mode?
* I think the build increased because we now load the full typescript compiler as part of the editor, there isn't a great way around this, except making sure that lazy loading works really well (is doing an await in the store initialization a problem?)
* Yes, the vite patch is while I wait for https://github.com/vitejs/vite/pull/2494, which is for Firefox support

**Comment by amoutonbrady** [comment]
Yeah, so I merged it on a special branch for now.

I pushed a couple of visual fixes that makes it almost as good as it use to be but with all the niceties you added.

If you can tackle the flickering bit that would be A-MAZ-ING. We always had it because of two way binding.. It was less noticeable on codemirror but still there.

Reading a bit here and there, it appears that Monaco doesn't seem to properly parse JSX for highlighting. You see in my screenshot, it seems like `<button>` isn't being highlighted and that the attribute `type` is but not `onClick`. It's not crazy bad but yeah. Sounds like it's not related to theme. I found this package : [https://www.npmjs.com/package/monaco-jsx-highlighter](https://www.npmjs.com/package/monaco-jsx-highlighter) which might be helpful. 

image

Ah, you even made a PR to vite, wonderful!

**Comment by modderme123** [comment]
I'd be happy to create another PR with JSX syntax highlighting and flickering. I assume I should split the flickering and jsx into two PRs

**Pull request merged**
